apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  labels:
    app: mikroservisi
    tier: backend
spec:
  containers:
    - name: backend
      image: cordarjovana/mikroservisi:backend
      ports:
        - containerPort: 1337
  imagePullSecrets:
    - name: myregistrykey