apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  labels:
    app: mikroservisi
spec:
  containers:
    - name: backend
      image: cordarjovana/mikroservisi:backend
      ports:
        - containerPort: 1337
  imagePullSecrets:
    - name: myregistrykey

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: mikroservisi
spec:
  ports:
    - port: 1337
      targetPort: 1337
  selector:
    app: mikroservisi

