apiVersion: v1
kind: Pod
metadata:
  name: database
  labels:
    app: mikroservisi
spec:
  containers:
    - name: database
      image: cordarjovana/mikroservisi:database
      ports:
        - containerPort: 4185
  imagePullSecrets:
    - name: myregistrykey

---
apiVersion: v1
kind: Service
metadata:
  name: database-service
  labels:
    app: mikroservisi
spec:
  ports:
    - port: 4185
      targetPort: 4185
  selector:
    app: mikroservisi
