apiVersion: v1
kind: Pod
metadata:
  name: exams-pod
  labels:
    app: mikroservisi
    tier: exams
spec:
  containers:
    - name: exams
      image: cordarjovana/mikroservisi:exams
      ports:
        - containerPort: 9000
  imagePullSecrets:
    - name: myregistrykey
---
apiVersion: v1
kind: Service
metadata:
  name: exams
  labels:
    app: mikroservisi
    tier: exams
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: mikroservisi
    tier: exams
