apiVersion: v1
kind: Pod
metadata:
  name: exams-pod
  labels:
    app: mikroservisi
    tier: exams
spec:
  containers:
    - name: exams
      image: cordarjovana/mikroservisi:exams
      ports:
        - containerPort: 9000
  imagePullSecrets:
    - name: myregistrykey