apiVersion: v1
kind: Pod
metadata:
  name: exams
  labels:
    app: mikroservisi
spec:
  containers:
    - name: exams
      image: cordarjovana/mikroservisi:exams
      ports:
        - containerPort: 9000
  imagePullSecrets:
    - name: myregistrykey

---
apiVersion: v1
kind: Service
metadata:
  name: exams-service
  labels:
    app: mikroservisi
spec:
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: mikroservisi
