apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: mikroservisi
spec:
  containers:
    - name: frontend
      image: cordarjovana/mikroservisi:frontend
      ports:
        - containerPort: 3000
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "200m"
  imagePullSecrets:
    - name: myregistrykey
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
     app: mikroservisi
spec:
   type: LoadBalancer
   ports:
     - port: 3000
       targetPort: 3000
   selector:
     app: mikroservisi
