apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: mikroservisi
spec:
  containers:
    - name: frontend
      image: cordarjovana/mikroservisi:frontend
      ports:
        - containerPort: 3000
  imagePullSecrets:
    - name: myregistrykey

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
     app: mikroservisi
spec:
   type: LoadBalancer
   ports:
     - port: 3000
       targetPort: 3000
   selector:
     app: mikroservisi

