apiVersion: v1
kind: Pod
metadata:
  name: mikroservisi-exams-pod
  labels:
    name: mikroservisi-exams-pod
    app: mikroservisi
spec:
  containers:
    - name: exams-1
      image: cordarjovana/mikroservisi:exams
      ports:
        - containerPort: 9000
  imagePullSecrets:
    - name: myregistrykey
