apiVersion: v1
kind: Service
metadata:
  name: mikroservisi-frontend-service
  labels:
    app: mikroservisi
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: mikroservisi
