apiVersion: v1
kind: Pod
metadata:
  name: mikroservisi-frontend-pod
  labels:
    app: mikroservisi
spec:
  containers:
    - name: frontend-1
      image: cordarjovana/mikroservisi:frontend
      ports:
        - containerPort: 3000
  imagePullSecrets:
    - name: myregistrykey
