apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    name: backend-service
    app: mikroservisi
spec:
  ports:
    - port: 1337
      targetPort: 1337
  selector:
    name: backend
    app: mikroservisi
