apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: mikroservisi
spec:
  containers:
    - name: frontend
      image: cordarjovana/mikroservisi:frontend
      ports:
        - containerPort: 3000
  imagePullSecrets:
    - name: myregistrykey
