apiVersion: v1
kind: Pod
metadata:
  name: exams
  labels:
    name: exams
    app: mikroservisi
spec:
  containers:
    - name: exams
      image: exams
      ports:
        - containerPort: 9000
  imagePullSecrets:
    - name: myregistrykey
