apiVersion: v1
kind: Service
metadata:
  name: exams-service
  labels:
    name: exams-service
    app: mikroservisi
spec:
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    name: exams
    app: mikroservisi
