apiVersion: v1
kind: Pod
metadata:
  name: mikroservisi-phpmyadmin-pod
  labels:
    name: mikroservisi-phpmyadmin-pod
    app: mikroservisi
spec:
  containers:
    - name: pma
      image: cordarjovana/mikroservisi:phpmyadmin
      ports:
        - containerPort: 80
      env:
        - name: PMA_HOST
          value: "mysql"
        - name: PMA_PORT
          value: "3306"
        - name: PMA_ARBITRARY
          value: "1"
