apiVersion: v1
kind: Pod
metadata:
  name: database
  labels:
    name: database
    app: mikroservisi
spec:
  containers:
    - name: database
      image: cordarjovana/mikroservisi:database
      ports:
        - containerPort: 4185
  imagePullSecrets:
    - name: myregistrykey
