apiVersion: v1
kind: Service
metadata:
  name: database-service
  labels:
    name: database-service
    app: mikroservisi
spec:
  ports:
    - port: 4185
      targetPort: 4185
  selector:
    name: database
    app: mikroservisi
