apiVersion: v1
kind: Pod
metadata:
  name: mikroservisi-backend-pod
  labels:
    name: mikroservisi-backend-pod
    app: mikroservisi
spec:
  containers:
    - name: backend-1
      image: cordarjovana/mikroservisi:backend
      ports:
        - containerPort: 1337
  imagePullSecrets:
    - name: myregistrykey
