apiVersion: v1
kind: Service
metadata:
  name: mikroservisi-phpmyadmin-service
  labels:
    name: mikroservisi-phpmyadmin-service
    app: mikroservisi
spec:
  selector:
    name: mikroservisi-phpmyadmin-pod
    app: mikroservisi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
