apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    name: db
    app: mikroservisi
spec:
  imagePullSecrets:
    - name: myregistrykey
  containers:
    - name: mysql
      image: mysql:5.7
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "my_secret_password"
        - name: MYSQL_DATABASE
          value: "app_db"
        - name: MYSQL_USER
          value: "db_user"
        - name: MYSQL_PASSWORD
          value: "db_user_pass"
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: dbdata
          mountPath: /var/lib/mysql
  volumes:
    - name: dbdata
      emptyDir: {}
