apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mikroservisi
spec:
  imagePullSecrets:
    - name: myregistrykey
  containers:
    - name: mysql
      image: cordarjovana/mikroservisi:mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "my_secret_password"
        - name: MYSQL_DATABASE
          value: "estudent"
        - name: MYSQL_USER
          value: "db_user"
        - name: MYSQL_PASSWORD
          value: "db_user_pass"
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: dbdata
          mountPath: /var/lib/mysql
  volumes:
    - name: dbdata
      emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: mikroservisi
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mikroservisi