apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  estudent.sql: |
    CREATE DATABASE IF NOT EXISTS estudent;
    USE estudent;

    CREATE TABLE archive (
      id int(11) NOT NULL,
      createdAt bigint(20) DEFAULT NULL,
      fromModel varchar(255) DEFAULT NULL,
      originalRecord longtext DEFAULT NULL,
      originalRecordId longtext DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

    CREATE TABLE ispit (
      createdAt bigint(20) DEFAULT NULL,
      updatedAt bigint(20) DEFAULT NULL,
      id int(11) NOT NULL,
      datum datetime DEFAULT NULL,
      ispitniRok int(11) DEFAULT NULL,
      predmet int(11) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

    INSERT INTO ispit (createdAt, updatedAt, id, datum, ispitniRok, predmet) VALUES
    (NULL, NULL, 4, '2023-06-16 16:30:00', 4, 1),
    (NULL, NULL, 5, '2023-06-17 16:30:00', 4, 2),
    (NULL, NULL, 6, '2023-06-18 16:30:00', 4, 5),
    (NULL, NULL, 7, '2023-06-19 16:30:00', 4, 6),
    (NULL, NULL, 8, '2023-06-20 16:30:00', 4, 3),
    (NULL, NULL, 9, '2023-06-21 16:30:00', 4, 4),
    (NULL, NULL, 10, '2023-06-22 16:30:00', 4, 7),
    (NULL, NULL, 11, '2023-06-23 16:30:00', 4, 8),
    (NULL, NULL, 12, '2023-08-17 16:34:34', 6, 1),
    (NULL, NULL, 13, '2023-08-18 16:34:34', 6, 2),
    (NULL, NULL, 14, '2023-08-19 16:34:34', 6, 5),
    (NULL, NULL, 15, '2023-08-20 16:34:34', 6, 6),
    (NULL, NULL, 16, '2023-08-21 16:34:34', 6, 3),
    (NULL, NULL, 17, '2023-08-22 16:34:34', 6, 4),
    (NULL, NULL, 18, '2023-08-23 16:34:34', 6, 7),
    (NULL, NULL, 19, '2023-08-24 16:34:34', 6, 8),
    (NULL, NULL, 20, '2023-09-07 16:36:47', 7, 1),
    (NULL, NULL, 21, '2023-09-08 16:36:47', 7, 2),
    (NULL, NULL, 22, '2023-09-09 16:36:47', 7, 5),
    (NULL, NULL, 23, '2023-09-10 16:36:47', 7, 6),
    (NULL, NULL, 24, '2023-09-11 16:36:47', 7, 3),
    (NULL, NULL, 25, '2023-09-12 16:36:47', 7, 4),
    (NULL, NULL, 26, '2023-09-13 16:36:47', 7, 7),
    (NULL, NULL, 27, '2023-09-14 16:36:47', 7, 8),
    (NULL, NULL, 28, '2023-06-20 16:45:24', 4, 9),
    (NULL, NULL, 29, '2023-06-21 16:45:24', 4, 10),
    (NULL, NULL, 30, '2023-06-23 16:45:24', 4, 11),
    (NULL, NULL, 31, '2023-06-24 16:45:24', 4, 12),
    (NULL, NULL, 32, '2023-08-19 16:47:15', 6, 9),
    (NULL, NULL, 33, '2023-08-20 16:47:15', 6, 10),
    (NULL, NULL, 34, '2023-08-21 16:47:15', 6, 11),
    (NULL, NULL, 35, '2023-08-22 16:47:15', 6, 12),
    (NULL, NULL, 36, '2023-09-08 16:48:32', 7, 9),
    (NULL, NULL, 37, '2023-09-09 16:48:32', 7, 10),
    (NULL, NULL, 38, '2023-09-10 16:48:32', 7, 11),
    (NULL, NULL, 39, '2023-09-11 16:48:32', 7, 12);

    CREATE TABLE ispitnirok (
      createdAt bigint(20) DEFAULT NULL,
      updatedAt bigint(20) DEFAULT NULL,
      id int(11) NOT NULL,
      naziv varchar(255) DEFAULT NULL,
      datumPocetka datetime DEFAULT NULL,
      datumKraja datetime DEFAULT NULL,
      datumPocetkaPrijave datetime DEFAULT NULL,
      datumZavrsetkaPrijave datetime DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

    INSERT INTO ispitnirok (createdAt, updatedAt, id, naziv, datumPocetka, datumKraja, datumPocetkaPrijave, datumZavrsetkaPrijave) VALUES
    (NULL, NULL, 1, 'Јануарски', '2023-01-15 17:42:37', '2023-01-31 17:42:37', '2023-01-01 17:42:37', '2023-01-15 17:42:37'),
    (NULL, NULL, 2, 'Фебруарски', '2023-02-15 17:42:37', '2023-02-28 17:42:37', '2023-02-01 17:42:37', '2023-02-15 17:42:37'),
    (NULL, NULL, 3, 'Априлски', '2023-04-10 17:42:37', '2023-04-26 17:42:37', '2023-04-01 17:42:37', '2023-04-08 17:42:37'),
    (NULL, NULL, 4, 'Јунски', '2023-06-14 17:42:37', '2023-06-30 17:42:37', '2023-06-01 17:42:37', '2023-06-10 17:42:37'),
    (NULL, NULL, 5, 'Јулски', '2023-07-14 17:42:37', '2023-07-30 17:42:37', '2023-07-01 17:42:37', '2023-07-10 17:42:37'),
    (NULL, NULL, 6, 'Август', '2023-08-16 17:42:37', '2023-09-01 17:42:37', '2023-07-29 17:42:37', '2023-08-15 17:42:37'),
    (NULL, NULL, 7, 'Септембарски', '2023-09-07 17:42:37', '2023-09-14 17:42:37', '2023-09-01 17:42:37', '2023-09-06 17:42:37'),
    (NULL, NULL, 8, 'Октобарски', '2023-09-25 17:42:37', '2023-09-30 17:42:37', '2023-09-15 17:42:37', '2023-09-18 17:42:37');

    CREATE TABLE predmet (
      createdAt bigint(20) DEFAULT NULL,
      updatedAt bigint(20) DEFAULT NULL,
      id int(11) NOT NULL,
      naziv varchar(255) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

    INSERT INTO predmet (createdAt, updatedAt, id, naziv) VALUES
    (NULL, NULL, 1, 'Рачунарске мреже'),
    (NULL, NULL, 2, 'Оперативни системи'),
    (NULL, NULL, 3, 'Софтверски инжењеринг'),
    (NULL, NULL, 4, 'Математика'),
    (NULL, NULL, 5, 'Мултимедијални системи'),
    (NULL, NULL, 6, 'Веб дизајн'),
    (NULL, NULL, 7, 'Управљање пројектима'),
    (NULL, NULL, 8, 'Електротехника'),
    (NULL, NULL, 9, 'Микропроцесори'),
    (NULL, NULL, 10, 'Енглески језик'),
    (NULL, NULL, 11, 'Микрорачунараски системи'),
    (NULL, NULL, 12, 'Архитектура рачунара');

    CREATE TABLE student (
      createdAt bigint(20) DEFAULT NULL,
      updatedAt bigint(20) DEFAULT NULL,
      id int(11) NOT NULL,
      brojIndeksa varchar(255) DEFAULT NULL,
      datumRodjenja datetime DEFAULT NULL,
      ime varchar(255) DEFAULT NULL,
      prezime varchar(255) DEFAULT NULL,
      pol varchar(255) DEFAULT NULL,
      upisaniSemestar int(11) DEFAULT NULL,
      upisanaGodina int(11) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

    INSERT INTO student (createdAt, updatedAt, id, brojIndeksa, datumRodjenja, ime, prezime, pol, upisaniSemestar, upisanaGodina) VALUES
    (NULL, NULL, 1, '2020/0041', '1998-08-14 18:00:00', 'Nikola', 'Tesla', 'M', 2, 1),
    (NULL, NULL, 2, '2020/0037', '1997-02-14 18:00:00', 'Mihajlo', 'Pupin', 'M', 3, 2),
    (NULL, NULL, 3, '2020/0004', '1999-03-20 18:00:00', 'Milutin', 'Milanković', 'M', 1, 1),
    (NULL, NULL, 4, '2020/0052', '1998-07-10 18:00:00', 'Ruđer', 'Bošković', 'M', 2, 1),
    (NULL, NULL, 5, '2020/0011', '1999-05-21 18:00:00', 'Mileva', 'Marić', 'F', 3, 2);

    CREATE TABLE sv20 (
      createdAt bigint(20) DEFAULT NULL,
      updatedAt bigint(20) DEFAULT NULL,
      id int(11) NOT NULL,
      jmbg double DEFAULT NULL,
      maternjiJezik varchar(255) DEFAULT NULL,
      vrstaSrednjeSkole varchar(255) DEFAULT NULL,
      drzavaSrednjeSkole varchar(255) DEFAULT NULL,
      opstinaSrednjeSkole varchar(255) DEFAULT NULL,
      nazivSrednjeSkole varchar(255) DEFAULT NULL,
      godinaZavrsetkaSrednjeSkole double DEFAULT NULL,
      bracniStatus varchar(255) DEFAULT NULL,
      drzavaPrebivalista varchar(255) DEFAULT NULL,
      opstinaPrebivalista varchar(255) DEFAULT NULL,
      mestoPrebivalista varchar(255) DEFAULT NULL,
      adresaPrebivalista varchar(255) DEFAULT NULL,
      kontaktTelefon varchar(255) DEFAULT NULL,
      drzavaTokomStudija varchar(255) DEFAULT NULL,
      opstinaTokomStudija varchar(255) DEFAULT NULL,
      adresaTokomStudija varchar(255) DEFAULT NULL,
      tipSmestajaTokomStudija varchar(255) DEFAULT NULL,
      nacinIzdrzavanjaTokomStudija varchar(255) DEFAULT NULL,
      zaposlenje tinyint(1) DEFAULT NULL,
      izdrzavanjeDrugogLica varchar(255) DEFAULT NULL,
      zaposlenjeRoditelja tinyint(1) DEFAULT NULL,
      zanimanjeRoditelja varchar(255) DEFAULT NULL,
      skolskaSpremaRoditelja varchar(255) DEFAULT NULL,
      potrebanVidPodrske varchar(255) DEFAULT NULL,
      student int(11) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

    ALTER TABLE archive
      ADD PRIMARY KEY (id),
      ADD UNIQUE KEY id (id);

    ALTER TABLE ispit
      ADD PRIMARY KEY (id),
      ADD UNIQUE KEY id (id),
      ADD KEY FK_ISPIT_ISPITNI_ROK (ispitniRok),
      ADD KEY FK_ISPIT_PREDMET (predmet);

    ALTER TABLE ispitnirok
      ADD PRIMARY KEY (id),
      ADD UNIQUE KEY id (id);

    ALTER TABLE nastava
      ADD PRIMARY KEY (id),
      ADD UNIQUE KEY id (id),
      ADD KEY FK_NASTAVA_PREDMET (predmet),
      ADD KEY FK_NASTAVA_PROFESOR (profesor);

    ALTER TABLE obavestenja
      ADD PRIMARY KEY (id);

    ALTER TABLE ocena
      ADD PRIMARY KEY (id),
      ADD UNIQUE KEY id (id),
      ADD KEY FK_OCENA_PRIJAVA (prijava),
      ADD KEY FK_OCENA_PROFESOR (profesor);

    ALTER TABLE praksa
      ADD PRIMARY KEY (id),
      ADD UNIQUE KEY id (id),
      ADD UNIQUE KEY pib (pib);

    ALTER TABLE predavanje
      ADD PRIMARY KEY (id),
      ADD UNIQUE KEY id (id),
      ADD KEY FK_PREDAVANJE_PREDMET (predmet),
      ADD KEY FK_PREDAVANJE_STUDENT (student);

    ALTER TABLE predmet
      ADD PRIMARY KEY (id),
      ADD UNIQUE KEY id (id),
      ADD KEY FK_PREDMET_SEMESTAR (semestar);

    ALTER TABLE prijava
      ADD PRIMARY KEY (id),
      ADD UNIQUE KEY id (id),
      ADD KEY FK_PRIJAVA_STUDENT (student),
      ADD KEY FK_PRIJAVA_ISPIT (ispit);

    ALTER TABLE profesor
      ADD PRIMARY KEY (id),
      ADD UNIQUE KEY id (id),
      ADD UNIQUE KEY jmbg (jmbg);

    ALTER TABLE semestar
      ADD PRIMARY KEY (id),
      ADD UNIQUE KEY id (id);

    ALTER TABLE student
      ADD PRIMARY KEY (id),
      ADD UNIQUE KEY id (id),
      ADD UNIQUE KEY indeks (indeks),
      ADD UNIQUE KEY korisnickoIme (korisnickoIme),
      ADD UNIQUE KEY sifra (sifra),
      ADD KEY FK_STUDENT_SEMESTAR (semestar);

    ALTER TABLE sv20
      ADD PRIMARY KEY (id),
      ADD UNIQUE KEY id (id),
      ADD UNIQUE KEY jmbg (jmbg);

    ALTER TABLE archive
      MODIFY id int(11) NOT NULL AUTO_INCREMENT;

    ALTER TABLE ispit
      MODIFY id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=41;

    ALTER TABLE ispitnirok
      MODIFY id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;

    ALTER TABLE nastava
      MODIFY id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=16;

    ALTER TABLE obavestenja
      MODIFY id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

    ALTER TABLE ocena
      MODIFY id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

    ALTER TABLE praksa
      MODIFY id int(11) NOT NULL AUTO_INCREMENT;

    ALTER TABLE predavanje
      MODIFY id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;

    ALTER TABLE predmet
      MODIFY id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;

    ALTER TABLE prijava
      MODIFY id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1511112;

    ALTER TABLE profesor
      MODIFY id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;

    ALTER TABLE semestar
      MODIFY id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;

    ALTER TABLE student
      MODIFY id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;

    ALTER TABLE sv20
      MODIFY id int(11) NOT NULL AUTO_INCREMENT;

    ALTER TABLE ispit
      ADD CONSTRAINT ispit_ibfk_1 FOREIGN KEY (ispitniRok) REFERENCES ispitnirok (id),
      ADD CONSTRAINT ispit_ibfk_2 FOREIGN KEY (predmet) REFERENCES predmet (id);

    ALTER TABLE nastava
      ADD CONSTRAINT nastava_ibfk_1 FOREIGN KEY (predmet) REFERENCES predmet (id),
      ADD CONSTRAINT nastava_ibfk_2 FOREIGN KEY (profesor) REFERENCES profesor (id);

    ALTER TABLE ocena
      ADD CONSTRAINT ocena_ibfk_1 FOREIGN KEY (prijava) REFERENCES prijava (id),
      ADD CONSTRAINT ocena_ibfk_2 FOREIGN KEY (profesor) REFERENCES profesor (id);

    ALTER TABLE predavanje
      ADD CONSTRAINT predavanje_ibfk_1 FOREIGN KEY (predmet) REFERENCES predmet (id),
      ADD CONSTRAINT predavanje_ibfk_2 FOREIGN KEY (student) REFERENCES student (id);

    ALTER TABLE predmet
      ADD CONSTRAINT predmet_ibfk_1 FOREIGN KEY (semestar) REFERENCES semestar (id);

    ALTER TABLE prijava
      ADD CONSTRAINT prijava_ibfk_1 FOREIGN KEY (student) REFERENCES student (id),
      ADD CONSTRAINT prijava_ibfk_2 FOREIGN KEY (ispit) REFERENCES ispit (id);

    ALTER TABLE student
      ADD CONSTRAINT student_ibfk_1 FOREIGN KEY (semestar) REFERENCES semestar (id);
    COMMIT;

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: mysql-disk
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mikroservisi
spec:
  imagePullSecrets:
    - name: myregistrykey
  containers:
    - name: mysql
      image: cordarjovana/mikroservisi:mysql
      args:
        - "--ignore-db-dir=lost+found"
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "my_secret_password"
        - name: MYSQL_DATABASE
          value: "estudent"
        - name: MYSQL_USER
          value: "db_user"
        - name: MYSQL_PASSWORD
          value: "db_user_pass"
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: dbdata
          mountPath: /var/lib/mysql
        - name: initdb
          mountPath: /docker-entrypoint-initdb.d
  initContainers:
    - name: init-mysql
      image: busybox
      command:
        - sh
        - -c
        - test ! -f /docker-entrypoint-initdb.d/estudent.sql && cp /config/estudent.sql /docker-entrypoint-initdb.d/estudent.sql || echo "Init script already present"
      volumeMounts:
        - name: initdb
          mountPath: /docker-entrypoint-initdb.d
        - name: config
          mountPath: /config
  volumes:
    - name: dbdata
      persistentVolumeClaim:
        claimName: mysql-pvc
    - name: config
      configMap:
        name: mysql-initdb-config
    - name: initdb
      emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: mikroservisi
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mikroservisi
