apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  estudent.sql: |
    SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
    START TRANSACTION;
    SET time_zone = "+00:00";

    CREATE TABLE archive (
      id int(11) NOT NULL,
      createdAt bigint(20) DEFAULT NULL,
      fromModel varchar(255) DEFAULT NULL,
      originalRecord longtext DEFAULT NULL,
      originalRecordId longtext DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

    CREATE TABLE ispit (
      createdAt bigint(20) DEFAULT NULL,
      updatedAt bigint(20) DEFAULT NULL,
      id int(11) NOT NULL,
      datum datetime DEFAULT NULL,
      ispitniRok int(11) DEFAULT NULL,
      predmet int(11) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

    INSERT INTO ispit (createdAt, updatedAt, id, datum, ispitniRok, predmet) VALUES
    (NULL, NULL, 4, '2024-06-16 16:30:00', 4, 1),
    (NULL, NULL, 5, '2024-06-17 16:30:00', 4, 2),
    (NULL, NULL, 6, '2024-06-18 16:30:00', 4, 5),
    (NULL, NULL, 7, '2024-06-19 16:30:00', 4, 6),
    (NULL, NULL, 8, '2024-06-20 16:30:00', 4, 3),
    (NULL, NULL, 9, '2024-06-21 16:30:00', 4, 4),
    (NULL, NULL, 10, '2024-06-22 16:30:00', 4, 7),
    (NULL, NULL, 11, '2024-06-23 16:30:00', 4, 8),
    (NULL, NULL, 12, '2024-08-17 16:34:34', 6, 1),
    (NULL, NULL, 13, '2024-08-18 16:34:34', 6, 2),
    (NULL, NULL, 14, '2024-08-19 16:34:34', 6, 5),
    (NULL, NULL, 15, '2024-08-20 16:34:34', 6, 6),
    (NULL, NULL, 16, '2024-08-21 16:34:34', 6, 3),
    (NULL, NULL, 17, '2024-08-22 16:34:34', 6, 4),
    (NULL, NULL, 18, '2024-08-23 16:34:34', 6, 7),
    (NULL, NULL, 19, '2024-08-24 16:34:34', 6, 8),
    (NULL, NULL, 20, '2024-09-07 16:36:47', 7, 1),
    (NULL, NULL, 21, '2024-09-08 16:36:47', 7, 2),
    (NULL, NULL, 22, '2024-09-09 16:36:47', 7, 5),
    (NULL, NULL, 23, '2024-09-10 16:36:47', 7, 6),
    (NULL, NULL, 24, '2024-09-11 16:36:47', 7, 3),
    (NULL, NULL, 25, '2024-09-12 16:36:47', 7, 4),
    (NULL, NULL, 26, '2024-09-13 16:36:47', 7, 7),
    (NULL, NULL, 27, '2024-09-14 16:36:47', 7, 8),
    (NULL, NULL, 28, '2024-06-20 16:45:24', 4, 9),
    (NULL, NULL, 29, '2024-06-21 16:45:24', 4, 10),
    (NULL, NULL, 30, '2024-06-23 16:45:24', 4, 11),
    (NULL, NULL, 31, '2024-06-24 16:45:24', 4, 12),
    (NULL, NULL, 32, '2024-08-19 16:47:15', 6, 9),
    (NULL, NULL, 33, '2024-08-20 16:47:15', 6, 10),
    (NULL, NULL, 34, '2024-08-21 16:47:15', 6, 11),
    (NULL, NULL, 35, '2024-08-22 16:47:15', 6, 12),
    (NULL, NULL, 36, '2024-09-08 16:48:32', 7, 9),
    (NULL, NULL, 37, '2024-09-09 16:48:32', 7, 10),
    (NULL, NULL, 38, '2024-09-10 16:48:32', 7, 11),
    (NULL, NULL, 39, '2024-09-11 16:48:32', 7, 12);

    CREATE TABLE ispitnirok (
      createdAt bigint(20) DEFAULT NULL,
      updatedAt bigint(20) DEFAULT NULL,
      id int(11) NOT NULL,
      naziv varchar(255) DEFAULT NULL,
      datumPocetka datetime DEFAULT NULL,
      datumKraja datetime DEFAULT NULL,
      datumPocetkaPrijave datetime DEFAULT NULL,
      datumZavrsetkaPrijave datetime DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

    INSERT INTO ispitnirok (createdAt, updatedAt, id, naziv, datumPocetka, datumKraja, datumPocetkaPrijave, datumZavrsetkaPrijave) VALUES
    (NULL, NULL, 1, 'Januarski', '2024-01-15 17:42:37', '2024-01-31 17:42:37', '2024-01-01 17:42:37', '2024-01-15 17:42:37'),
    (NULL, NULL, 2, 'Februarski', '2024-02-15 17:42:37', '2024-02-28 17:42:37', '2024-02-01 17:42:37', '2024-02-15 17:42:37'),
    (NULL, NULL, 3, 'Aprilski', '2024-04-10 17:42:37', '2024-04-26 17:42:37', '2024-04-01 17:42:37', '2024-04-08 17:42:37'),
    (NULL, NULL, 4, 'Junski', '2024-06-14 17:42:37', '2024-06-30 17:42:37', '2024-06-01 17:42:37', '2024-06-10 17:42:37'),
    (NULL, NULL, 5, 'Julski', '2024-07-14 17:42:37', '2024-07-30 17:42:37', '2024-07-01 17:42:37', '2024-07-10 17:42:37'),
    (NULL, NULL, 6, 'Avgust', '2024-08-16 17:42:37', '2024-09-01 17:42:37', '2024-07-29 17:42:37', '2024-08-15 17:42:37'),
    (NULL, NULL, 7, 'Septembarski', '2024-09-07 17:42:37', '2024-09-14 17:42:37', '2024-09-01 17:42:37', '2024-09-06 17:42:37'),
    (NULL, NULL, 8, 'Oktobarski', '2024-09-25 17:42:37', '2024-09-30 17:42:37', '2024-09-15 17:42:37', '2024-09-18 17:42:37');

    CREATE TABLE nastava (
      createdAt bigint(20) DEFAULT NULL,
      updatedAt bigint(20) DEFAULT NULL,
      id int(11) NOT NULL,
      profesor int(11) DEFAULT NULL,
      predmet int(11) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

    INSERT INTO nastava (createdAt, updatedAt, id, profesor, predmet) VALUES
    (NULL, NULL, 4, 2, 1),
    (NULL, NULL, 5, 2, 2),
    (NULL, NULL, 6, 2, 5),
    (NULL, NULL, 7, 2, 6),
    (NULL, NULL, 8, 5, 3),
    (NULL, NULL, 9, 5, 4),
    (NULL, NULL, 10, 6, 9),
    (NULL, NULL, 11, 6, 10),
    (NULL, NULL, 12, 4, 11),
    (NULL, NULL, 13, 4, 12),
    (NULL, NULL, 14, 3, 7),
    (NULL, NULL, 15, 1, 8);

    CREATE TABLE obavestenja (
      id int(11) NOT NULL,
      datumPocetka date NOT NULL,
      datumZavrsetka date NOT NULL,
      naslov varchar(255) NOT NULL,
      tekst varchar(255) NOT NULL,
      createdAt bigint(20) DEFAULT NULL,
      updatedAt bigint(20) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

    INSERT INTO obavestenja (id, datumPocetka, datumZavrsetka, naslov, tekst, createdAt, updatedAt) VALUES
    (1, '2024-06-19', '2024-09-30', 'Novo radno vreme Studentske sluzbe', 'Usled predstojecih praznika Studentska sluzba ce raditi od 12:00h do 14:00h od ponedeljka do srede.', 0, 0),
    (2, '2024-06-21', '2024-09-30', 'Otvaranje novih prostorija za studente', 'Od ponedeljka, 17.04.2024., nove prostorije na trecem spratu zgrade 2 ce biti otvorene za sve studente.', NULL, NULL);

    CREATE TABLE ocena (
      createdAt bigint(20) DEFAULT NULL,
      updatedAt bigint(20) DEFAULT NULL,
      id int(11) NOT NULL,
      ocena double DEFAULT NULL,
      profesor int(11) DEFAULT NULL,
      prijava int(11) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

    INSERT INTO ocena (createdAt, updatedAt, id, ocena, profesor, prijava) VALUES
    (NULL, NULL, 3, 10, 5, 13),
    (NULL, NULL, 4, 5, 6, 11),
    (NULL, NULL, 5, 5, 2, 12);

    CREATE TABLE praksa (
      createdAt bigint(20) DEFAULT NULL,
      updatedAt bigint(20) DEFAULT NULL,
      id int(11) NOT NULL,
      nazivKompanije varchar(255) DEFAULT NULL,
      pib double DEFAULT NULL,
      datumOd datetime DEFAULT NULL,
      datumDo datetime DEFAULT NULL,
      studentId int(11) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

    CREATE TABLE predavanje (
      createdAt bigint(20) DEFAULT NULL,
      updatedAt bigint(20) DEFAULT NULL,
      id int(11) NOT NULL,
      student int(11) DEFAULT NULL,
      predmet int(11) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

    INSERT INTO predavanje (createdAt, updatedAt, id, student, predmet) VALUES
    (NULL, NULL, 4, 1, 2),
    (NULL, NULL, 5, 1, 5),
    (NULL, NULL, 6, 1, 10),
    (NULL, NULL, 7, 1, 12),
    (NULL, NULL, 8, 1, 7);

    CREATE TABLE predmet (
      createdAt bigint(20) DEFAULT NULL,
      updatedAt bigint(20) DEFAULT NULL,
      id int(11) NOT NULL,
      nazivPredmeta varchar(255) DEFAULT NULL,
      espb double DEFAULT NULL,
      izborni tinyint(1) DEFAULT NULL,
      semestar int(11) DEFAULT NULL,
      website varchar(255) NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

    INSERT INTO predmet (createdAt, updatedAt, id, nazivPredmeta, espb, izborni, semestar, website) VALUES
    (NULL, NULL, 1, 'Matematika 1', 6, 0, 1, 'http://math.fon.bg.ac.rs/kursevi/matematika1'),
    (NULL, NULL, 2, 'Matematika 1', 6, 0, 2, 'http://math.fon.bg.ac.rs/kursevi/matematika1'),
    (NULL, NULL, 3, 'Menadzment', 6, 0, 1, 'http://men.fon.bg.ac.rs/'),
    (NULL, NULL, 4, 'Menadzment', 6, 0, 2, 'http://men.fon.bg.ac.rs/'),
    (NULL, NULL, 5, 'Matematika 2', 6, 0, 3, 'http://math.fon.bg.ac.rs/kursevi/matematika2'),
    (NULL, NULL, 6, 'Matematika 2', 6, 0, 4, 'http://math.fon.bg.ac.rs/kursevi/matematika2'),
    (NULL, NULL, 7, 'Programiranje 1', 6, 0, 3, 'http://silab.fon.bg.ac.rs/predmeti/osnovne-studije/programiranje-1/'),
    (NULL, NULL, 8, 'Sociologija', 4, 0, 4, 'http://hr.fon.bg.ac.rs/sociologija/'),
    (NULL, NULL, 9, 'Ekonomija', 6, 0, 1, 'http://ekonomija.fon.bg.ac.rs/'),
    (NULL, NULL, 10, 'Ekonomija', 6, 0, 2, 'http://ekonomija.fon.bg.ac.rs/'),
    (NULL, NULL, 11, 'Proizvodni sistemi', 6, 0, 3, 'http://imi.fon.bg.ac.rs/proizvodni-sistemi/'),
    (NULL, NULL, 12, 'Proizvodni sistemi', 6, 0, 4, 'http://imi.fon.bg.ac.rs/proizvodni-sistemi/');

    CREATE TABLE prijava (
      createdAt bigint(20) DEFAULT NULL,
      updatedAt bigint(20) DEFAULT NULL,
      id int(11) NOT NULL,
      datumPrijave datetime DEFAULT NULL,
      student int(11) DEFAULT NULL,
      ispit int(11) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

    INSERT INTO prijava (createdAt, updatedAt, id, datumPrijave, student, ispit) VALUES
    (NULL, NULL, 11, '2023-06-02 16:58:49', 1, 9),
    (NULL, NULL, 12, '2023-06-05 17:02:16', 1, 5),
    (NULL, NULL, 13, '2024-06-02 16:58:49', 1, 9),
    (NULL, NULL, 14, '2024-06-05 17:02:16', 1, 5),
    (NULL, NULL, 15, '2024-06-05 17:02:16', 1, 29);

    CREATE TABLE profesor (
      createdAt bigint(20) DEFAULT NULL,
      updatedAt bigint(20) DEFAULT NULL,
      id int(11) NOT NULL,
      ime varchar(255) DEFAULT NULL,
      prezime varchar(255) DEFAULT NULL,
      jmbg varchar(255) DEFAULT NULL,
      zvanje varchar(255) DEFAULT NULL,
      mail varchar(255) NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

    INSERT INTO profesor (createdAt, updatedAt, id, ime, prezime, jmbg, zvanje, mail) VALUES
    (NULL, NULL, 1, 'Petar', 'Petrovic', '23821328193279', 'DR', 'petar.petrovic@fon.bg.ac.rs'),
    (NULL, NULL, 2, 'Jovan', 'Jovanovic', '498274702109', 'MR', 'jovan.jovanovic@fon.bg.ac.rs'),
    (NULL, NULL, 3, 'Zivojin', 'Zivojinovic', '2844691289', 'DR', 'zivojin.zivojinovic@fon.bg.ac.rs'),
    (NULL, NULL, 4, 'Marko', 'Markovic', '2204761837', 'DR', 'marko.markovic@fon.bg.ac.rs'),
    (NULL, NULL, 5, 'Ana', 'Anic', '23456378', 'MR', 'ana.anic@fon.bg.ac.rs'),
    (NULL, NULL, 6, 'Petra', 'Petric', '456789', 'DR', 'petra.petric@fon.bg.ac.rs');

    CREATE TABLE semestar (
      createdAt bigint(20) DEFAULT NULL,
      updatedAt bigint(20) DEFAULT NULL,
      id int(11) NOT NULL,
      godinaStudija double DEFAULT NULL,
      brojSemestra double DEFAULT NULL,
      smer varchar(255) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

    INSERT INTO semestar (createdAt, updatedAt, id, godinaStudija, brojSemestra, smer) VALUES
    (NULL, NULL, 1, 1, 1, 'Menadzment'),
    (NULL, NULL, 2, 1, 1, 'ISIT'),
    (NULL, NULL, 3, 1, 2, 'ISIT'),
    (NULL, NULL, 4, 1, 2, 'Menadzment'),
    (NULL, NULL, 5, 2, 2, 'Menadzment'),
    (NULL, NULL, 6, 2, 1, 'Menadzment'),
    (NULL, NULL, 7, 2, 2, 'ISIT'),
    (NULL, NULL, 8, 2, 1, 'ISIT');

    CREATE TABLE student (
      createdAt bigint(20) DEFAULT NULL,
      updatedAt bigint(20) DEFAULT NULL,
      id int(11) NOT NULL,
      ime varchar(255) DEFAULT NULL,
      prezime varchar(255) DEFAULT NULL,
      indeks varchar(255) DEFAULT NULL,
      korisnickoIme varchar(255) DEFAULT NULL,
      sifra varchar(255) DEFAULT NULL,
      semestar int(11) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

    INSERT INTO student (createdAt, updatedAt, id, ime, prezime, indeks, korisnickoIme, sifra, semestar) VALUES
    (NULL, NULL, 1, 'Ivona', 'Petrovic', '2017-0246', '20170246', '20170246', 2),
    (NULL, NULL, 2, 'Jovana', 'Cordar', '2017-0066', '20170066', '20170066', 2),
    (NULL, NULL, 3, 'Nina', 'Mandic', '2017-0123', '20170123', '20170123', 1);

    CREATE TABLE sv20 (
      createdAt bigint(20) DEFAULT NULL,
      updatedAt bigint(20) DEFAULT NULL,
      id int(11) NOT NULL,
      jmbg double DEFAULT NULL,
      maternjiJezik varchar(255) DEFAULT NULL,
      vrstaSrednjeSkole varchar(255) DEFAULT NULL,
      drzavaSrednjeSkole varchar(255) DEFAULT NULL,
      opstinaSrednjeSkole varchar(255) DEFAULT NULL,
      nazivSrednjeSkole varchar(255) DEFAULT NULL,
      godinaZavrsetkaSrednjeSkole double DEFAULT NULL,
      bracniStatus varchar(255) DEFAULT NULL,
      drzavaPrebivalista varchar(255) DEFAULT NULL,
      opstinaPrebivalista varchar(255) DEFAULT NULL,
      mestoPrebivalista varchar(255) DEFAULT NULL,
      adresaPrebivalista varchar(255) DEFAULT NULL,
      kontaktTelefon varchar(255) DEFAULT NULL,
      drzavaTokomStudija varchar(255) DEFAULT NULL,
      opstinaTokomStudija varchar(255) DEFAULT NULL,
      adresaTokomStudija varchar(255) DEFAULT NULL,
      tipSmestajaTokomStudija varchar(255) DEFAULT NULL,
      nacinIzdrzavanjaTokomStudija varchar(255) DEFAULT NULL,
      zaposlenje tinyint(1) DEFAULT NULL,
      izdrzavanjeDrugogLica varchar(255) DEFAULT NULL,
      zaposlenjeRoditelja tinyint(1) DEFAULT NULL,
      zanimanjeRoditelja varchar(255) DEFAULT NULL,
      skolskaSpremaRoditelja varchar(255) DEFAULT NULL,
      potrebanVidPodrske varchar(255) DEFAULT NULL,
      student int(11) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

    ALTER TABLE archive
      ADD PRIMARY KEY (id),
      ADD UNIQUE KEY id (id);

    ALTER TABLE ispit
      ADD PRIMARY KEY (id),
      ADD UNIQUE KEY id (id),
      ADD KEY FK_ISPIT_ISPITNI_ROK (ispitniRok),
      ADD KEY FK_ISPIT_PREDMET (predmet);

    ALTER TABLE ispitnirok
      ADD PRIMARY KEY (id),
      ADD UNIQUE KEY id (id);

    ALTER TABLE nastava
      ADD PRIMARY KEY (id),
      ADD UNIQUE KEY id (id),
      ADD KEY FK_NASTAVA_PREDMET (predmet),
      ADD KEY FK_NASTAVA_PROFESOR (profesor);

    ALTER TABLE obavestenja
      ADD PRIMARY KEY (id);

    ALTER TABLE ocena
      ADD PRIMARY KEY (id),
      ADD UNIQUE KEY id (id),
      ADD KEY FK_OCENA_PRIJAVA (prijava),
      ADD KEY FK_OCENA_PROFESOR (profesor);

    ALTER TABLE praksa
      ADD PRIMARY KEY (id),
      ADD UNIQUE KEY id (id),
      ADD UNIQUE KEY pib (pib);

    ALTER TABLE predavanje
      ADD PRIMARY KEY (id),
      ADD UNIQUE KEY id (id),
      ADD KEY FK_PREDAVANJE_PREDMET (predmet),
      ADD KEY FK_PREDAVANJE_STUDENT (student);

    ALTER TABLE predmet
      ADD PRIMARY KEY (id),
      ADD UNIQUE KEY id (id),
      ADD KEY FK_PREDMET_SEMESTAR (semestar);

    ALTER TABLE prijava
      ADD PRIMARY KEY (id),
      ADD UNIQUE KEY id (id),
      ADD KEY FK_PRIJAVA_STUDENT (student),
      ADD KEY FK_PRIJAVA_ISPIT (ispit);

    ALTER TABLE profesor
      ADD PRIMARY KEY (id),
      ADD UNIQUE KEY id (id),
      ADD UNIQUE KEY jmbg (jmbg);

    ALTER TABLE semestar
      ADD PRIMARY KEY (id),
      ADD UNIQUE KEY id (id);

    ALTER TABLE student
      ADD PRIMARY KEY (id),
      ADD UNIQUE KEY id (id),
      ADD UNIQUE KEY indeks (indeks),
      ADD UNIQUE KEY korisnickoIme (korisnickoIme),
      ADD UNIQUE KEY sifra (sifra),
      ADD KEY FK_STUDENT_SEMESTAR (semestar);

    ALTER TABLE sv20
      ADD PRIMARY KEY (id),
      ADD UNIQUE KEY id (id),
      ADD UNIQUE KEY jmbg (jmbg);

    ALTER TABLE archive
      MODIFY id int(11) NOT NULL AUTO_INCREMENT;

    ALTER TABLE ispit
      MODIFY id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=41;

    ALTER TABLE ispitnirok
      MODIFY id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;

    ALTER TABLE nastava
      MODIFY id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=16;

    ALTER TABLE obavestenja
      MODIFY id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

    ALTER TABLE ocena
      MODIFY id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

    ALTER TABLE praksa
      MODIFY id int(11) NOT NULL AUTO_INCREMENT;

    ALTER TABLE predavanje
      MODIFY id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;

    ALTER TABLE predmet
      MODIFY id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;

    ALTER TABLE prijava
      MODIFY id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1511112;

    ALTER TABLE profesor
      MODIFY id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;

    ALTER TABLE semestar
      MODIFY id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;

    ALTER TABLE student
      MODIFY id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;

    ALTER TABLE sv20
      MODIFY id int(11) NOT NULL AUTO_INCREMENT;

    ALTER TABLE ispit
      ADD CONSTRAINT ispit_ibfk_1 FOREIGN KEY (ispitniRok) REFERENCES ispitnirok (id),
      ADD CONSTRAINT ispit_ibfk_2 FOREIGN KEY (predmet) REFERENCES predmet (id);

    ALTER TABLE nastava
      ADD CONSTRAINT nastava_ibfk_1 FOREIGN KEY (predmet) REFERENCES predmet (id),
      ADD CONSTRAINT nastava_ibfk_2 FOREIGN KEY (profesor) REFERENCES profesor (id);

    ALTER TABLE ocena
      ADD CONSTRAINT ocena_ibfk_1 FOREIGN KEY (prijava) REFERENCES prijava (id),
      ADD CONSTRAINT ocena_ibfk_2 FOREIGN KEY (profesor) REFERENCES profesor (id);

    ALTER TABLE predavanje
      ADD CONSTRAINT predavanje_ibfk_1 FOREIGN KEY (predmet) REFERENCES predmet (id),
      ADD CONSTRAINT predavanje_ibfk_2 FOREIGN KEY (student) REFERENCES student (id);

    ALTER TABLE predmet
      ADD CONSTRAINT predmet_ibfk_1 FOREIGN KEY (semestar) REFERENCES semestar (id);

    ALTER TABLE prijava
      ADD CONSTRAINT prijava_ibfk_1 FOREIGN KEY (student) REFERENCES student (id),
      ADD CONSTRAINT prijava_ibfk_2 FOREIGN KEY (ispit) REFERENCES ispit (id);

    ALTER TABLE student
      ADD CONSTRAINT student_ibfk_1 FOREIGN KEY (semestar) REFERENCES semestar (id);
    COMMIT;

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: mysql-disk
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mikroservisi
spec:
  imagePullSecrets:
    - name: myregistrykey
  containers:
    - name: mysql
      image: cordarjovana/mikroservisi:mysql
      args:
        - "--ignore-db-dir=lost+found"
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "my_secret_password"
        - name: MYSQL_DATABASE
          value: "estudent"
        - name: MYSQL_USER
          value: "db_user"
        - name: MYSQL_PASSWORD
          value: "db_user_pass"
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: dbdata
          mountPath: /var/lib/mysql
        - name: initdb
          mountPath: /docker-entrypoint-initdb.d
  initContainers:
    - name: init-mysql
      image: busybox
      command:
        - sh
        - -c
        - test ! -f /docker-entrypoint-initdb.d/estudent.sql && cp /config/estudent.sql /docker-entrypoint-initdb.d/estudent.sql || echo "Init script already present"
      volumeMounts:
        - name: initdb
          mountPath: /docker-entrypoint-initdb.d
        - name: config
          mountPath: /config
  volumes:
    - name: dbdata
      persistentVolumeClaim:
        claimName: mysql-pvc
    - name: config
      configMap:
        name: mysql-initdb-config
    - name: initdb
      emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: mikroservisi
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mikroservisi
